languageCode = "en-us"
title = "MatchMeta.Info - AMI Artifact Pipeline Status"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "MatchMeta.Info"
  homepage = "https://github.com/jblukach/matchmeta"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
mainSections = ["posts"]

[[params.socials]]
name = "Archive"
link = "https://github.com/4n6ir/matchmeta.info"

[[params.socials]]
name = "GetMeta"
link = "https://pypi.org/project/getmeta/"

[[params.socials]]
name = "Pipeline"
link = "https://github.com/jblukach/matchmeta"

[[params.socials]]
name = "RSS Feed"
link = "/index.xml"

[[params.socials]]
name = "Subscription"
link = "https://jblukach.gumroad.com/l/AMZNHASH"
